{
    'Two Crows': 'CDL2CROWS',
    'Three Outside Down': 'CDL3OUTSIDE',
    'Advance Block': 'CDLADVANCEBLOCK',
    'Belt-hold': 'CDLBELTHOLD',
    'Bearish Closing Marubozu': 'CDLCLOSINGMARUBOZU',
    'Counterattack': 'CDLCOUNTERATTACK',
    'Dark Cloud Cover': 'CDLDARKCLOUDCOVER',
    'Doji Star': 'CDLDOJISTAR',
    'Engulfing Pattern': 'CDLENGULFING',
    'Evening Doji Star': 'CDLEVENINGDOJISTAR',
    'Evening Star': 'CDLEVENINGSTAR',
    'Down Gap side-by-side white lines': 'CDLGAPSIDESIDEWHITE',
    'Gravestone Doji': 'CDLGRAVESTONEDOJI',
    'Hanging Man': 'CDLHANGINGMAN',
    'Harami Pattern': 'CDLHARAMI',
    'Harami Cross Pattern': 'CDLHARAMICROSS',
    'High-Wave Candle': 'CDLHIGHWAVE',
    'Bearish Long Line Candle': 'CDLLONGLINE',
    'Bearish Marubozu': 'CDLMARUBOZU',
    'On-Neck Pattern': 'CDLONNECK',
    'Bearish Separating Lines': 'CDLSEPARATINGLINES',
    'Shooting Star': 'CDLSHOOTINGSTAR',
    'Tasuki Gap': 'CDLTASUKIGAP',
    'Bearish Spinning Top': 'CDLSPINNINGTOP',
}

