{
    'Hammer': 'CDLHAMMER',
    'Piercing Pattern': 'CDLPIERCING',
    'Engulfing Pattern': 'CDLENGULFING',
    'Morning Star': 'CDLMORNINGSTAR',
    'Three White Soldiers': 'CDL3WHITESOLDIERS',
    'Three Inside Up': 'CDL3INSIDE',
    'Belt-hold': 'CDLBELTHOLD',
    'Bullish Closing Marubozu': 'CDLCLOSINGMARUBOZU',
    'Counterattack': 'CDLCOUNTERATTACK',
    'Doji': 'CDLDOJI',
    'Doji Star': 'CDLDOJISTAR',
    'Dragonfly Doji': 'CDLDRAGONFLYDOJI',
    'Up Gap side-by-side white lines': 'CDLGAPSIDESIDEWHITE',
    'Harami Pattern': 'CDLHARAMI',
    'Harami Cross Pattern': 'CDLHARAMICROSS',
    'High-Wave Candle': 'CDLHIGHWAVE',
    'Homing Pigeon': 'CDLHOMINGPIGEON',
    'Inverted Hammer': 'CDLINVERTEDHAMMER',
    'Ladder Bottom': 'CDLLADDERBOTTOM',
    'Bullish Long Line Candle': 'CDLLONGLINE',
    'Bullish Marubozu': 'CDLMARUBOZU',
    'Matching Low': 'CDLMATCHINGLOW',
    'Morning Doji Star': 'CDLMORNINGDOJISTAR',
    'Bullish Separating Lines': 'CDLSEPARATINGLINES',
    'Takuri': 'CDLTAKURI',
    'Bullish Spinning Top': 'CDLSPINNINGTOP',

}
